import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar/Navbar";
import Footer from "@/components/navigation/Footer/Footer";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["100", "400"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
